name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: echo ${GITHUB_REF}
      
      - name: Build
        run: g++ -DECB -DENC -std=c++17 -maes -msse4.1 Nist.cpp -o Nist

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: Nist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

