name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: g++ -DECB -DENC -std=c++17 -maes -msse4.1 Nist.cpp -o Nist

      - name: Deliverable
        uses: actions/upload-artifact@v2
        with:
          name: Deliverable
          path: Nist
          retention-days: 7
